console.log("Hello Jan");
console.log("How do you do?");
console.log("       *       ");
console.log("      ***      ");
console.log("     *****     ");
console.log("    *******    ");
console.log("   *********   ");
console.log("  ***********  ");
console.log(" ************* ");
console.log("***************");